
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-11T11:37:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "08bea7067e350303eead533b471aa60697b3b8c3",
 "version": "v3.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
